### PR TITLE
Make Auto Transaction Execution flag permanent in DB

### PR DESCRIPTION
**Pull request by wolfsolver**

### CODE REVIEW

**Comment by guanlisheng** [comment]
Using preference storge today might be better.  SQLite3 persist is good for per-database configuration.

**Comment by wolfsolver** [comment]
> Using preference storge today might be better. SQLite3 persist is good for per-database configuration.

Can you better explain? Right now, without this fix, if I clear app storage on android and reopen file, switch is not maintened.

**Comment by wolfsolver** [comment]
After thinking in this I get your point.

- it's not correct to store this preference into DB for an issue on specific thirds parts application (like OneDrive)
- for uniformity is better also to move from InfoKey to shared preferences also:
  - DEFAULT_ACCOUNT_ID
  - SHOW_OPEN_ACCOUNTS
  - SHOW_FAVOURITE_ACCOUNTS

**Comment by guanlisheng** [comment]
thanks.

default_account_id should be per database while the remaining two are good to store in app's preference store.

**Pull request closed without merging**
