### PR TITLE
Floating button on splits

### PR DESCRIPTION
**Pull request by MisterY**
Implementation of #129

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
Just out of curiosity, why did you "extracting fragment into a separate file"?

**Comment by MisterY** [comment]
Mostly because I find it much simpler to understand what is going on when classes are in separate files. It makes the interaction between a fragment and an activity a bit cleaner, too, I believe.
Let me know if you prefer otherwise.

**Comment by MisterY** [comment]
Btw, I often update existing comments instead of adding new ones so I'm not sure if you get updates for those via email.

**Comment by AlessandroLazzari** [comment]
There are no problems. I just wanted to know if there was a technical
reason that you had brought to choose to separate the fragment from the
Activity. Everything is ok. Tonight I do the tests and do the merge.

**Comment by MisterY** [comment]
Thanks! 
In case you get any issues with the merge, then you can just merge one and I'll rebase the other pull request and resubmit.

**Pull request merged**
