### PR TITLE
Move DBPref into SharedPreference

### LINKED ISSUE #1813: Move SHOW_OPEN_ACCOUNTS SHOW_FAVOURITE_ACCOUNTS into SharedPrference
default_account_id should be per database while the remaining two are good to store in app's preference store.

_Originally posted by @guanlisheng in https://github.com/moneymanagerex/android-money-manager-ex/issues/1809#issuecomment-2327593780_

### PR DESCRIPTION
**Pull request by wolfsolver**
close #1813

@guanlisheng need to also prepare remove old entry from DB? if yes how to do? 
query is:
DELETE FROM INFOTABLE_V1 where key = "android:show_open_accounts" or key = "android:show_fav_accounts"

### CODE REVIEW

**Comment by wolfsolver** [comment]
@guanlisheng second question: need to keep old flag (so in main try to read from infokey and move into sharedPreference)? or is not necessary

**Comment by guanlisheng** [comment]
hi @wolfsolver, better to migrate historical data from DB. then it will be no impact to end users.

**Comment by wolfsolver** [comment]
@guanlisheng  I try to implement the code. This read from DB and delete old entryes.
Tested on my device

**Comment by guanlisheng** [comment]
we can leave the old records/entries.

**Comment by wolfsolver** [comment]
why? this can make confusion in future developent...

**Comment by guanlisheng** [comment]
then we can keep the code clean; these two old entries will cause big problems for old users.

**Comment by wolfsolver** [comment]
But if we keep ald value how can we migrate preference from dB to shared preferences? At every start there is entry in dB and we reload old (inconsistent) value. Let me do an example
- program start and read dB pref and store in shared
- user change value in setting and this value is store into shared
- user restart program and old dB entry is reload from dB instead shared preferences

**Comment by guanlisheng** [comment]
if that's the case,  let's skip the migration either.  just wanted to keep code neat.

actually, share preference setting should have higher priority if the related setting exists.

**Comment by wolfsolver** [comment]
done. remember to put a note into release to adivice user to set preference since they are not migrated

**Review by guanlisheng — APPROVED** [review]

**Pull request merged**
