### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
@guanlisheng are there any strings which you would like to merge?

**Comment by guanlisheng** [comment]
fastlane related are good

**Comment by ovari** [comment]
> fastlane related are good

Sorry, do not understand your comment. What are "fastlane"? Thank you

**Comment by guanlisheng** [comment]
hi @ovari
sorry for the late, `fastlane` means this path https://github.com/moneymanagerex/android-money-manager-ex/tree/master/fastlane/metadata/android and it is for f-droid.


btw, can you take some time on android mmex as well?

**Comment by ovari** [comment]
> btw, can you take some time on android mmex as well?

@guanlisheng where is the link on Crowdin and Github? Looking at strings then say where to update them on GitHub.

**Comment by guanlisheng** [comment]
1. https://desktop-crowdin.moneymanagerex.org/
2. https://android-crowdin.moneymanagerex.org/

it would be found in our forum via https://forum.moneymanagerex.org/viewtopic.php?t=11009

**Comment by guanlisheng** [comment]
closed as this pr has some conflicts

**Comment by ovari** [comment]
Can you please merge https://github.com/moneymanagerex/moneymanagerex/pull/6631 before conflict might occur?

**Comment by ovari** [comment]
> closed as this pr has some conflicts

If redone with the same changes, can it be merged without conflicts?

**Comment by guanlisheng** [comment]
if the changes are fine, it will be merged shortly. just as your other ones for homepage.

**Comment by ovari** [comment]
Doing this using a web-browser.

Are you able to do a global find and replace for:
* `Recurring`... → `Scheduled`
* `Home page` → `Dashboard`
* `Export to` → `Export as`
etc.

?

**Comment by ovari** [comment]
> if the changes are fine, it will be merged shortly. just as your other ones for homepage.

Was there any strings in this issue that you closed without merging that are not fine?

**Comment by guanlisheng** [comment]
I left some comments weeks ago and I think you can continue sending handy PR(s)

**Pull request closed without merging**
