### PR TITLE
Add date adjustment buttons to quick set previous/next day.

### PR DESCRIPTION
**Pull request by vladimir-poleh**
Added buttons to increase/decrease date without date picker opening. Affected views: Edit Transaction and Edit Recurring Transaction. 
Investment Edit is not using date from the UI at all.

### CODE REVIEW

**Comment by MisterY** [comment]
Hi, Vladimir. What do you mean by the last sentence? Did you look at the Portfolio edit or a Watchlist?
Thanks for these improvements.

**Comment by vladimir-poleh** [comment]
If you have account with "Investment" type and adding new stock, edit view allows to select date, but in the reality Stock object will be initialized with current date and value from the UI will not be applied.
It's not related to this pull request, I just explained why quick adjustments buttons were added only on two edit views.

**Comment by MisterY** [comment]
Right, I understand. However, that's clearly a bug introduced by me being hasty. :) You know, trying to do one thing that requires another that requires another that...
I'll add that as a separate issue and then we can apply the same behaviour in the investment record editor.
I'll check and merge these later when I'm back to a PC.

**Comment by MisterY** [comment]
This works fine. I'm just looking at how to add the "button effect" on touch.

**Comment by vladimir-poleh** [comment]
`android:background="?attr/selectableItemBackground"` is working. Just need to think what controls should have this effect and how to apply it with minimal changes.

**Comment by MisterY** [comment]
I've already added it to the date next/prev controls. Revisiting this code gave me a few ideas:
- in the forms where models (i.e. transactionEntity) have been introduced, remove the use of tags for dates  and other values
- use the "click-effect" on other buttons, where appropriate (I've added them to the calculator, which is very convenient)
This is what I'm shuffling with currently (and fixing null-exceptions). See the latest commits. 
Please keep in mind that certain areas of the code are quite ancient as the code was maintained since the Eclipse days so any improvements are welcome.

**Pull request merged**
