### PR TITLE
Enable AutoExecution only if ShowNotification

### LINKED ISSUE #1812: AutoPost is part of notifiction process
AutoPost is part of notifiction process (so every day at 8:00 new transaction will be posted).

For better experience is better to disable autopost flag is notification is not set, as in commit https://github.com/wolfsolver/android-money-manager-ex/commit/6c88f473b34848fcc6f3b4087d25c8749381fa41

_Originally posted by @wolfsolver in https://github.com/moneymanagerex/android-money-manager-ex/issues/1683#issuecomment-2326808915_ reporter by @islam2hamy

### PR DESCRIPTION
**Pull request by wolfsolver**
Close #1812

### CODE REVIEW

**Comment by guanlisheng** [comment]
seems the goal is to honor both settings. can you apply the logic at the caller?

**Comment by wolfsolver** [comment]
Not in a fast way :)
I suggest to merge this and than start for refactoring

**Comment by guanlisheng** [comment]
Furthermore, we can only keep notifications and remove the global autoExecute config. 
this will also simplify Behavior setting.  

thanks to your transaction-level configuration, which makes the simplification possible

**Comment by wolfsolver** [comment]
@guanlisheng can you see my comment ok https://github.com/moneymanagerex/android-money-manager-ex/issues/1812#issuecomment-2329118321

**Comment by wolfsolver** [comment]
> Furthermore, we can only keep notifications and remove the global autoExecute config. this will also simplify Behavior setting.
> 
> thanks to your transaction-level configuration, which makes the simplification possible

I agree, We can keep only one switch as "Enable Noticiation & AutoPost" and remove old "AutoPost", clear code using the correct bejavioir for transaction:
* Auto ==> Auto
* Prompt ==> Notification
* None ==> No notificaion (right now the system show notif also for this)

this can also help futher refirement for new logic coming corm desktop version

**Pull request closed without merging**
