### PR TITLE
Negative split amounts

### PR DESCRIPTION
**Pull request by MisterY**
Fix for #309.
Negative total is not allowed on Split Categories screen.

### CODE REVIEW

**Comment by Douki31** [comment]
Hi There,
I have checked the modification using V2.2.1 (Build 622)
Main transaction is Credit, and 2 lines are created using Split function.

Both lines have a positive amount with Credit type. (See Attached 11-47-07)
It appears the Error Window (See Attached 11-49-37) and it is not possible to validate as is.

To recover I use the following trick (See Attached 11-47-41)
Lines are Negative with a Type Withdrawal.

Hope it will help you to fix the problem.

screenshot_2015-05-25-11-47-05
screenshot_2015-05-25-11-49-37
screenshot_2015-05-25-11-47-41

**Comment by Douki31** [comment]
Sorry for the photo reference but the import function didnot retreive the photo name.
11-47-07 is the first one
11-49-37 the second
11-47-41 the Third.

**Comment by Douki31** [comment]
It looks like the Amount in Split Line is using the sign of the Main Transaction, and not the Sign of the Split line.

**Comment by MisterY** [comment]
Hi, thanks for the screenshots! I have identified the reason for this. The transaction type comparison is using the localized text. I am fixing it right now.

**Comment by MisterY** [comment]
This has been properly handled in 2.2.2. Please try with this version.

**Comment by Douki31** [comment]
I test it and it works fine (with 2.2.3 build 624)
I also tested Credit Main Transaction with a split category containing one withdrawal and one credit. It works great, and you have the error message when total amount is negative.
Thanks again.

**Comment by MisterY** [comment]
Thank you very much for the confirmation, Cedric! 
I was thinking to automatically change the transaction type but this way the behaviour is consistent with the desktop version.
And thanks for finding and pointing out the issue.

**Pull request merged**
