### PR TITLE
update copyright to 2019

### PR DESCRIPTION
**Pull request by funrider1**
update copyright to 2019 and drop google plus entries

ok, this time everything is right ... hopefully :-)

### CODE REVIEW

**Comment by funrider1** [comment]
@mistery Do I have to do something or can do/help/support, so that this pull request is included in one of the next releases?

**Comment by funrider1** [comment]
@mistery i replaced all copyright 2018 with 2019 and the diff-view in changes area show me that lines with 2018 are deleted and such with 2019 are included.

Regarding the wrong changed licenses i want you to tell me how i can identify the right  files and differ these from the wrong ones? Thanx 

I will drop this pull request and create one for Google+ issue and an other one for copyright challange :-)

**Comment by MisterY** [comment]
@funrider1, thanks for the effort. Basically, only the licenses for MoneyManagerEx should be updated. It takes a while to go through each individual file and confirm that only the year has changed in licenses that were generated by us (and not in code that is used from other Open Source projects).
This is what I need to do, anyway, before merging these changes and, as you can guess, it is quite time consuming considering the number of affected files. :)

**Comment by MisterY** [comment]
This is what I mean:
image

**Comment by funrider1** [comment]
@MisterY I understand, this takes some time and is a bad job. :-O

then i leave the pull request open and wait a little bit. :-)

**Comment by MisterY** [comment]
I still see the license changes, i.e.  money/src/main/java/info/javaperformance/money/AbstractMoney.java, so can't merge this as-is. Sorry!

**Comment by funrider1** [comment]
ok, i will do it again and correct

**Comment by MisterY** [comment]
I'm sure you now understand how much effort is required to maintain even a fairly small app as this one. :)

**Pull request closed without merging**
