### PR TITLE
unify Category in both Recurring Transaction and Transaction list with neested category

### PR DESCRIPTION
**Pull request by wolfsolver**
close issue #1558 and improve #1559 

next step: adapt edit transaction to select nested category (actually only view nested category on ammex)

### CODE REVIEW

**Comment by guanlisheng** [comment]
Will this cause a double-counting issue? 
can you point out how MMEX4Destkop handles the nest categories? 

saying
`
A->B
B->C
C->D`

then the is a 1$ transaction with category D, what will the data (from your queries) look like?

**Comment by guanlisheng** [comment]
@luisdev any thought?

**Comment by wolfsolver** [comment]
I Will share a couple of screen tomorrow morning.

I haven't see any issue on mobile. Data is shown in list in a correct way. right now is still not possible to edit third level on mobile.

Any category is shown as "root" category. For example
Cat 1 : Sub 1.1 : Sub 1.2

**Comment by guanlisheng** [comment]
great and going to merge it into the master branch once the static check passes.
https://app.codacy.com/gh/moneymanagerex/android-money-manager-ex/pullRequest?prid=13598145

**Comment by wolfsolver** [comment]
I take a look to codacy, but didn't understand how to fix. Sqllite doesn't support set statement
Any suggestions?

**Review by guanlisheng — APPROVED** [review]
reference: https://www.sqlite.org/lang_with.html

**Comment by wolfsolver** [comment]
Yesterday I spend some time, but didn't understand how to fix codacy check. I need help thanks

**Pull request merged**
