### PR TITLE
Basic support for loan and shares accounts

### PR DESCRIPTION
**Pull request by Spoker**
Added basic support for loan and shares account.
* Name on homescreen
* Icon on homescreen

### CODE REVIEW

**Comment by Spoker** [comment]
The travis console tells me I need to accept licenses. I think I have done this locally? Is this just a travis setting or do I need to change something locally as well?

```
* What went wrong:
A problem occurred configuring project ':MMEX_Icon_Font'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26, Android SDK Build-Tools 27.0.1].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by MisterY** [comment]
Don't worry. I have not managed to get travis working properly yet so it is not a valid indicator, unfortunately. It will be very useful once in operation, though.

**Comment by MisterY** [comment]
Thanks for the contribution! You're a fully-fledged MMEX Android developer now! ;)

**Comment by MisterY** [comment]
I will add the new string keys to CrowdIn. Please submit any translations there as they will get overwritten the next time the translations get updated. Thanks!

**Pull request merged**
