### PR TITLE
Search icon on dashboard

### PR DESCRIPTION
**Pull request by MisterY**
Implementation of #87

### CODE REVIEW

**Comment by MisterY** [comment]
Not thoroughly tested.

**Comment by MisterY** [comment]
OK, done as you suggested. This is great!

**Comment by AlessandroLazzari** [comment]
It all works quite well. With the exception of the tablet mode in landscape layout, as you can see from the image below.

device-2015-05-03-170809

The solution could be:

1. change the icon for the transaction search
2. or in the menu item for the tablet with the horizontal layout, instead of displaying the icon, display the text

**Comment by AlessandroLazzari** [comment]
To release the 2.0 version, I've implemented that in the tablet version in the horizontal layout does not display the icon. I have not implemented all of the pull request, but only the code related to home_menu.xml and everything connected to this file.

**Comment by MisterY** [comment]
Hey, Ale,
Hope the kidney stone is not giving you too much trouble.I am starting with some preparatory work for the .qif export from the search results page. Now I want to add some options to the action bar and I am considering whether it would be beneficial to have a separate activity for the search results, or to continue using the fragment inside the Search Activity. I am interested in the differences between the layouts for the phones vs tablets.For that I created a Nexus 10 tablet image but the application layout I'm getting there is still exactly the same as for the phones. Could you tell me how to get the layout that you have in the screenshot below? I'd like to test the differences in behaviour between the two versions but I'm not sure how to get the tablet layout.
Ciao

**Pull request closed without merging**
