### PR TITLE
Save collapsed groups on dashboard

### PR DESCRIPTION
**Pull request by MisterY**
Implementation of #59.
Makes the dashboard more convenient to use.

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
I find this implementation is very well done! Congratulations!
A question: what is the new class AppSettings?
I found a problem that, however, does not depend on your code. When you have many accounts, and you scroll the list down, and then back on, is set the wrong icon for the group.
@MisterY  Can you fix?

**Comment by MisterY** [comment]
Thanks, Ale!
The AppSettings just makes it easier to access the settings from elsewhere in the application. I was thinking to put the settings constants in there, as well, so that everything is in one place. Maybe there is an easier way to access the settings that I don't know about.

What I would like to have in the end, is a class that has methods for each setting, so that there is no need to have all these constants around. And it takes care of reading and writing the setting values.
I'll have a look at that issue.

**Comment by MisterY** [comment]
I created #162 to track it.

**Comment by AlessandroLazzari** [comment]
Ok I will take a look at the code of this new class, to see if we can unify
with other code scattered in other classes such as Core or
MoneyManagerApplication

**Comment by MisterY** [comment]
I think the most user-friendly option would be to offer getters and setters for each setting. That way one does not have to think about details when a quick access to a setting/preference is needed. We can do it as we go, if you agree with the approach.

**Comment by AlessandroLazzari** [comment]
It was the way I had started to go down in the application. For this you
will find some function already present in the classes that I have written
above. Try to verify.
This reclamation of the code we keep as a last step, since there are
different branches in development.
What do you think?
​

**Comment by MisterY** [comment]
Yes, sure. I would not go and change it now. No need to change the code that works.
We can simply refactor things as we work on other issues that use such code. Then we move settings one by one to the Settings class. It is easier to control the migration that way. 
You'll see what I mean later when there's more changes that use settings. Right now I implemented only the minimum needed to get the group visibility preferences working. Even though the settings class is not 100% how I'd like it to look in the end.

**Pull request merged**
