### PR TITLE
Native tutorial

### PR DESCRIPTION
**Pull request by MisterY**
Implementing tutorial as android views, using SVGImageView for displaying the vector images.

### CODE REVIEW

**Comment by MisterY** [comment]
Have a look, please, and let me know if anything should be modified. Thanks!

**Comment by MisterY** [comment]
here's a splash screen as a bonus ;)

**Comment by MisterY** [comment]
The last commit completes #68.

**Comment by AlessandroLazzari** [comment]
Everything is ok. The new tutorial is really good! The structure of splash it's ok, but if you don't mind I make a little change: the background green with a dollar white as the icon of the launcher. See the below image
device-2015-03-27-214531
Now I merge your pull request and then I will change background_logo.xml. 
For the rest, great job!

**Pull request merged**
