### PR TITLE
please check some minor changes

### PR DESCRIPTION
**Pull request by funrider1**
It wasn't the biggest job and challenge to change 2018 in 2019 now, but i've started to contribute and practise how this works. If i'm wrong please explain wahts wrong and what i can do better. thanx

### CODE REVIEW

**Comment by MisterY** [comment]
The first tip would be to check the Copyright handling options in Android Studio. There was, at least in the previous versions, an option to add the copyright text as the copyright and the studio would update all the files correctly, i.e. - XML/HTML files, Java files, etc. ;)
That might simplify your life.
Other than that - it's a great start. Thank you very much for the contribution. I will merge this when I'm back to my development environment.

**Comment by MisterY** [comment]
An important thing is to submit pull requests to Dev branch. You can merge these changes from your master to dev and then submit a pull request on Dev branch.
Master in MMEX is a stable branch. This is the code that goes to the Release version of the app. At least it still is, until the distribution via F-Droid starts. The things may change at that point, depending on the limitations imposed by that channel.

**Comment by funrider1** [comment]
Currently I'm still struggling with the installation and configuration of Android Studio.  The things you write here probably refer to github, I have to get used to it. For the moment i did not unterstand any word :-)

**Comment by MisterY** [comment]
That means you're learning a lot. No worries, it will come in time. :)

**Pull request closed without merging**
