### PR TITLE
Add 'Count of transactions' to the list of transactions.

### PR DESCRIPTION
**Pull request by kazinci**
Hello!

At my bank in order to reduce the account management fee I need to use my bank card at least 30 times in a month. It is very tiring to count the transactions, because every time you want to know how many transaction you made in the current month you must count it by hand.
I already searched for similar applications on Play market but none of them can do this. Finally I found this project and I'm impressed how many opportunities it offers, how many features are already included and how many can be added. It could be the best money manager app on Google Play store (or maybe it is already the best). And on more thing, it is very beautiful!

I already made the modifications, please review it and contact me if there is something wrong. I also translated the missing hungarian phrases on crowdin (now it is on 100%).

Best Regards,
Zoltan.

### CODE REVIEW

**Comment by MisterY** [comment]
Hi, Zoltan,

Thank you very much for the contribution! I am glad that you like the project and the app. It is great to see your enthusiasm and I'm looking forward to your participation in development. Thank you also for contributing the translations. Much appreciated.
I have a couple of comments on the added feature.
- Placing the record count in the list header takes too much screen real-estate. I agree that the count is a good idea and I hope we can find a more practical place to put it. For example, the Search result list has a footer with the record count and the sum. But the footer approach might not work best for the account transactions list because the list could be quite long. Hopefully we come up with something more versatile. I have been thinking for a while about adding an expandable header (#485) that would contain filters and display the current options and would be a good place for the record count.
- The header layout file comes in 3 versions: portrait, landscape, and wide landscape. This change is included only in the portrait version. Just something to keep in mind for later.

After trying this out and considering the options, I'm starting to think that the filter/info dialog would be the best idea. It would provide enough space to display additional information as well as more detailed filtering and sorting options. The toolbar is getting rather full and adding more options is not practical although it would be useful. See "option 2" in the item #485.
The existing filters could be moved to the new dialog fragment along with the extra info such as record count and the existing account balances. This would also provide the ability to have users change the sorting of the records.
Let me know what you think. I might create an initial version in the coming days and you are also more than welcome to contribute both code and ideas.
In the meantime, you can run the version that has your change applied on top of the existing code, in case this information is important. Hope we can have a working version soon.

**Comment by kazinci** [comment]
First of all thank you for your quick reply and that you are considering to add the count feature to the app. It would be very useful for me, and I think for others as well.
Yes I agree with you, placing it to the header wasn't the best idea, especially for those who are using it on a relatively small screen.
Moving the filters/info to a new dialog sounds great, I'm getting excited to see it already. It would be a good place to add new filters/infos/features later on if they are comes up.
I also have a couple of other ideas that could improve usability of the app, but I think after adding the counting feature it will be the best of the money manager apps I've ever seen!

**Comment by MisterY** [comment]
Happy that you like the idea!
To resolve your current issue, I would recommend a couple of possible workarounds:

- run the search for the account transactions in the current month and check the transaction count in the footer.
- use the custom build of the app with the changes contained in this request.

These are both temporary until the first version of the filter dialog is created.
As mentioned earlier, I was hoping to add additional filters and sorting options but the toolbar was getting crowded on the phones. Having a separate dialog would solve this issue with a better layout and an overview of the currently applied filters, etc.
Should you wish to add features, please just add them to the backlog so we can be aware of what's going on and what to expect in the coming releases. Cheers!

**Comment by kazinci** [comment]
Ok, no problem, I gonna use my version until the next release then.
Thank you very much!

**Comment by vomikan** [comment]
@kazinci FYI 
The PC vertion of Money manager Ex is compatable this adnroid version.
You can open the same DB on PC and run Custom Report like this:
~~~~~
select 
strftime('%m-%Y', c.TRANSDATE) as month,
count(*) from CHECKINGACCOUNT_V1 c, ACCOUNTLIST_V1 a
where a.ACCOUNTID=c.ACCOUNTID
and a.ACCOUNTTYPE='Credit Card'
and c.TRANSDATE >= datetime('now', 'start of month', '-6 months')
group by month
~~~~~

For more info: https://sourceforge.net/p/moneymanagerex/wiki/General%20Report%20Manager/

PC mmex: https://sourceforge.net/projects/moneymanagerex/

**Comment by kazinci** [comment]
Hi vomikan,
Thank you for the hint, I knew about the PC version, and I think its also a very useful software. But I very rarely using it, that's why I thought about adding this feature to the app. But enabling the ability to allow the users to create and save such kind of reports in the Android version of MoneyManagerEx is also not a bad idea, don't you think so?
On the other hand it will be much more useful if it is visible somewhere on the UI immediately, so the users does not need to switch between the transaction list and the reports.

**Comment by MisterY** [comment]
Got the initial version working with the info dialog. Coming out in the next release.

**Comment by kazinci** [comment]
Wow, you extremely fast! I've seen the initial version and it looks pretty good: just what i needed! Thank you very much!

**Pull request closed without merging**
