### PR TITLE
Enhanced budgeting

### PR DESCRIPTION
**Pull request by tkasa**
I've been using Money Manager Ex for months now and I have some ideas to improve the budgeting part.

Changes in this PR:
 - Added coloring for the values in the "Actual" column in budgets whether they are above/below the planned amount.
 - Added a Settings panel for budgets and added a simplified budget view where the frequency is hidden and only the difference of planned and actual amounts are shown. The intention behind this is to reduce the amount of information on this list; hopefully this makes it easier to understand the current status of the cash flow just by glancing on the figures. This is somewhat related to #804.
- Amended BudgetActivity to only use fragment back stack in single panel UI.

 Planned changes:
 - New setting to open the current budget (if exists) when choosing Budgets from the navigation drawer.
 - Ability to edit budget entries.
 - Ability to add transactions to a category straight from a budget.
 - Cache and/or preload the computed amounts for categories in order to make the UI faster.
 - Summary row at the top of a budget with planned and actual expenses/income.

Any feedback is welcome.

### CODE REVIEW

**Comment by MisterY** [comment]
Great! Thanks a lot for the contribution.
I'll be back home mid-January and will then review and merge the pull request.
I can't see it in this app, did you send the request to the Dev branch? If not, please do so sometime in the next two weeks. Then I could easily publish a Beta version for wider testing from there.
You can also keep adding commits to this request until it is merged.
Thanks!

**Comment by tkasa** [comment]
This is indeed a request to the dev branch, so no problem there.
I'll keep pushing the subsequent features to this branch as I go.

Thanks!

**Comment by MisterY** [comment]
Excellent! Welcome to the project and happy new year!

**Comment by tkasa** [comment]
Happy new year!

Regarding the recent commits: I've implemented a way to handle the budget entry periods, and in the meantime I discovered that categories without actual budget entries are not listed when you open a budget, so I'll probably tackle that next.

**Comment by MisterY** [comment]
I've spent the whole evening just updating the development environment, not having much time to test the feature itself. Therefore I have merged the code and will publish a new Beta so that it can be tested by the community. Thanks again!

**Comment by MisterY** [comment]
Just a quick note regarding the implementation. 
The budgets are stored in a specific table, containing only the categories budgeted by the user. We can use the current functionality as an intermediary until the full budget editing is available.

**Comment by tkasa** [comment]
Can you please elaborate? I'm not sure what you mean. I'm using that budget
entry table to build the cache. Do you think that table should be queried
directly without the cache?
It might be just a superfluous addition, I'm not exactly a full-time
Android developer, so any feedback or suggestion is welcome.

I'll try to keep an eye out for budget-related issues and thanks for
pushing out the beta so soon.

**Comment by MisterY** [comment]
Hi!
What I mean is that there is a table in the database, called BudgetTable_V1. Once a user creates a budget and selects which categories to track, those categories are stored in this table together with the budget amounts. A user must be able to select, edit, and remove the tracked categories.
This is not a critique but an explanation on how the Budgets work in MMEX. The Android app has to match the features that exist in the other platform versions of the application.

Your addition is welcome as it is a step forward in that direction. Up to now only the first part of budget editing was completed.

Please do not feel any burden in writing code. None of the previous or existing developers are professional Android developers. We all do this as a hobby, in our spare time. No deadlines. Please feel free to learn and improve the app. That way we all gain something.

**Comment by tkasa** [comment]
Thanks for the explanation and encouragement. I've used the desktop application as a reference during the implementation and I will continue to do so. I agree that the all the versions should have the same features. 

So far development is far from a burden, I'll probably have a few new PRs in the coming months. :)

**Comment by MisterY** [comment]
You're always welcome! Please do get in touch should you have any questions at all.

**Pull request merged**
