### PR TITLE
f-droid fastlane: update Arabic and add Dutch

### PR DESCRIPTION
**Pull request by guanlisheng**

### CODE REVIEW

**Comment by islam2hamy** [comment]
Hello @guanlisheng ,
there is more updates in other Arabic language files
why i couldn't see them in this PR ?

**Comment by guanlisheng** [comment]
not sure which piece is missing. can you send a PR to have them?

**Comment by islam2hamy** [comment]
Text from the application
Init database categories

**Comment by islam2hamy** [comment]
Sorry i don't know how to PR from Crowdin

**Comment by islam2hamy** [comment]
> Sorry i don't know how to PR from Crowdin

@guanlisheng ?

**Comment by guanlisheng** [comment]
you can build and download the translated strings from Crowdin, then copy them into mmex source code and send PR.

**Comment by islam2hamy** [comment]
i am so sorry but i am really don't know how to do that
also i don't know why my translation did not appear on your build

ee0e1edd-2390-4eaa-aa76-3ce797f8ed37

**Pull request merged**
