### PR TITLE
Added Fix for #1188 and #1231

### PR DESCRIPTION
**Pull request by velmuruganc**
Added an option to enable edit screen popup or notification on sms receiving bank transaction updates

### CODE REVIEW

**Comment by andrepg** [comment]
I'm commenting here to keep in touch with this PR. I'm waiting this feature to teste with my S7 and change passcode buttons and make them bigger...

**Comment by MisterY** [comment]
@andrepg, you can also just click the Subscribe button. ;) Your feedback is appreciated, though.

**Comment by andrepg** [comment]
@MisterY I'm already subscribed to ALL repo. But I want to keep in touch more closely with this change in code because layout changes proposed here will impact my mods..

**Comment by MisterY** [comment]
Not sure if we're referring to the same thing. I meant this:

image

**Comment by andrepg** [comment]
Yeap @MisterY , we're talking about same feature. But, once I've subscribed and watch the entire repo, all threads and PR are like this:

image

I can't find an easy way to follow/subscribe to a specific thread, so here we are hehe. I'm just waiting, eager :)

**Comment by MisterY** [comment]
I'm still under impression that there is Subscribe for the whole repo and Subscribe on each individual issue. Try on an issue to which you're not subscribed, for example. Perhaps I'm wrong. Hard to tell from a mobile device but I remember subscribing to features I was interested in.

**Comment by HussienH** [comment]
The msg sender should be variable since each bank will have different sender it should be linked to account details

**Comment by velmuruganc** [comment]
@HussienH, msg sender is not fixed here and I am validting the msg is transaction msg or promotional msg. We no need to link the sender to account details bcz my logic will check the account number of that MMEX account. For example, I got msg like "Your Bank Visa Card Card ending with XXXX7337 has been reloaded with INR 12345.00 on 09-NOV-17 07:11 PM." in this case X7337 should be entered as account number field. Then my logic will extract the account no form the msg and findout the mapped account from MMEX db, then do the transaction. Please let me know if you want more details.

**Comment by HussienH** [comment]
Thanks for the info, my bank sends mlthe nickname of my card instead of thr number i will set it in the account
PS what about the current sms listener does it use the same logic?

**Comment by velmuruganc** [comment]
@HussienH, I have not handled the nick name and "Process bank trans" feature will look for the acct num. Could you please provide me the sample sms & SMS sender name, so that I can think of how I can handle

**Comment by HussienH** [comment]
Here you go,

Sales Draft LBP 47,000.00 at PHARMACIE MAAMOURA ROUAYSS LB using card HUSSEIN NEW CARD Remaining Bal. LBP 2,002,171.05 < 06/07/2018 05:00:19 GMT >

**Comment by HussienH** [comment]
This is exactly the message i received so no there is no dots

**Comment by velmuruganc** [comment]
@HussienH, ok thanks. I will make changes accordingly and share .apk file

**Comment by velmuruganc** [comment]
@HussienH, Also could you please provide me the sample sms for credit and transfer.

**Comment by HussienH** [comment]
Hi, i dont receive any sms for transfers, i only receive for card transactions

**Comment by velmuruganc** [comment]
@HussienH , I made changes as per your sample sms. Please update the your card num and add new payee as per below values. These changes are checked in to GitsHub

Card Number/Account Number : HUSSEIN NEW CARD 
Payee Name : PHARMACIE MAAMOURA ROUAYSS LB

With these info, I could see that the txn got created automatically as shown in the below snapshots.

image

If you want, please install the app from below link else wait for next beta.

https://www.dropbox.com/s/5xhdrnbvwgsq1yj/ammx-beta-2018.07.14.981.apk?dl=0

**Comment by HussienH** [comment]
Great thanks foe the update,  i will install the new version, but i have a question what will happen if the system did not find a payee?? Can we automatically create a new one and allocate it to unknown category untill the user changes the default category for this payee?

**Comment by velmuruganc** [comment]
Payee wont be added automatically. Automatic transaction wont happen if either account number or payee doestn't exists. So you can opt for either one of below options,

1. Enable SMS Transaction Status Notification option to show the transaction status msg in notification area. So that you can click the notification to invoke the MMEX edit trans screen. This will be displayed for failure and successful case. So that you can click notification to make the txn as reconciled.
2. Disable SMS Transaction Status Notification option to show the Edit Transaction screen. This may be annoying if you are working in some other app. This will be displayed only for failure case. If it is successful, then only toast msg will be displayed. 

Please make sure that you are enabling Process Bank Transaction SMS option under Settings > Behavior screen.

I hope this feature helps you to capture your txn automatically.

**Comment by velmuruganc** [comment]
Did you enabled following options? While enabling 1st, it will ask for reading sms, so here we need to allow the app to read the sms. Also could you please **share me the sms sender name**? For example, in my case "AX-CITIBK" the sms sender. 

We do have two different categories in sms, 1). transaction sms, 2). promotional sms. Transaction sms will have all string after hyphen (-) in the sms sender name. Promotional sms will have all numbers. My program will read only transaction sms.

This will not work if you are trying to send similar msg from any mobile.

image

**Comment by velmuruganc** [comment]
Ok, I got it. It is looking for "-" in the send and I made this as optional. Could you please try with below version.

https://www.dropbox.com/s/v6c7ojergdo3clp/ammx-beta-2018.07.19.981.apk?dl=0

**Pull request merged**
