### PR TITLE
adding clear button on amount entry (calculator)

### PR DESCRIPTION
**Pull request by MisterY**
Implementation of #161

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
Key is not implemented in landscape mode, and when the application you rotate it to crash

**Comment by MisterY** [comment]
aha, ok. Will have to try with the real device. :)

**Comment by AlessandroLazzari** [comment]
In the emulator, to simulate the rotation you need to press CTRL+F11

**Comment by MisterY** [comment]
:+1: thanks!

**Comment by MisterY** [comment]
Done & tested!

**Pull request merged**
