### PR TITLE
Split recurring transaction

### PR DESCRIPTION
**Pull request by MisterY**
Implementation of #40.

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
Tested your Pull Request. Everything is ok. There is only a small problem. If the reccuring transaction is split is not shown any category as you can see from the image below:

2015-03-29 16_20_42-clipboard

What do you think to set a fixed string?
I proceed with the merge the Pull Request.
Thanks

**Comment by MisterY** [comment]
Yes, we could link that to one of the issues I created earlier. I would like to display some indicator that this is a split transaction.
For example, Quicken displays '--Split--' for the category in such a case.

**Comment by AlessandroLazzari** [comment]
The Desktop application, what shows that I don't remember?

**Comment by MisterY** [comment]
Hah, in desktop version it is blank. At least we're consistent. ;)

I would suggest them use some text to indicate a split. Blank is confusing, in my opinion.

**Comment by MisterY** [comment]
Done! https://github.com/moneymanagerex/moneymanagerex/issues/427
We also have an issue about this on the list. There is quite a few items to work on now. :)

**Pull request merged**
