### PR TITLE
updating copyright to 2019 - hopefully all 

### PR DESCRIPTION
**Pull request by funrider1**
i used the bulk change function for copyright entries of android studio and hope i didn't break anything :-)

I merged to dev branch as specified.

### CODE REVIEW

**Comment by funrider1** [comment]
Build failed, but I have no idea for which , because I only changed copyright information which are comments in source code files 

Travis Tell me something about a Version Problem in project „:androidSVG“ ... what does that mean? Is it still possible to adopt the changes, or do I have to delete the pull request and start all over again? ;-)

**Comment by MisterY** [comment]
Don't worry, the build was failing before. Normally, your changes would not cause it to fail.
This test build should help before merging changes without having a dev environment at hand but it fails more often than not. Will have to check it out.
You do not need to make any modification to this request. I'll have a look at it once I sort out the F-Droid publishing issues. The new version has been in waiting for about two weeks now.

**Comment by MisterY** [comment]
As you can see:
```
Caused by: com.android.builder.errors.EvalIssueException: Failed to install the following Android SDK packages as some licences have not been accepted.
   platforms;android-28 Android SDK Platform 28
```
the error is in Travis configuration, not the source code, per se.
Hence, it increases the complexity. More often I've had to adapt the Travis configuration to fix the build rather than make real code changes. So I'm pondering on the usefulness of this whole feature.

**Comment by MisterY** [comment]
I think you can also pull the latest code, where I've added the SDK 28, and rebase your changes on top of that. That should result in a successful build, if you really want.
Otherwise, just leave as-is.

**Comment by funrider1** [comment]
Damn. I choosed the whole project for the mass change and not just the MMEX directories.

I close this pull request now, pull the latest code and going to do it again ... the third Time it will work for sure :-) ... this is for practice :-)

**Pull request closed without merging**
