### PR TITLE
fix(#1141): Add support for "N" as a code for "NONE" TransactionStatus

### PR DESCRIPTION
**Pull request by lexa2**
It was introduced in desktop MMEx 1.4.x.

### CODE REVIEW

**Comment by lexa2** [comment]
Looks like gradle recipe in Travis is broken ATM :-(.

**Comment by MisterY** [comment]
Yes, gradle went crazy again after the last update. It worked fine for a week, approximately. Could be caused by the update of the build tools.
Thanks for the contribution. Will check and include in the next beta release.

**Comment by MisterY** [comment]
However, this will probably not be enough to list the transactions correctly. There are probably multiple SQL queries that list transaction types explicitly. Further investigation is required to solve the real problem. I will include this patch but it will not make any visible changes, unfortunately.

**Comment by lexa2** [comment]
Sure, this change is just a start and as I had already admitted in related issue I'm not really a Java and/or Android developer/expert. As this change is an elementary one I just made a blind shot. And I know for sure that a more complicated logic change would be required to properly support new two-letter status format for transfer transactions (first letter for originating side and second letter for receiving side). I might give it a try but doing that blindly without the ability to compile and test the resulting code would be insane. Thus first challenge for me would be to set up Android build environment on a home workstation and only then move into trying to implement some changes.

**Comment by MisterY** [comment]
Absolutely. Everyone involved in development of this app is in the same situation. :)
Nobody here is a Java or Android developer and we all have to maintain a development environment if we want to make changes. That's how it works, I guess, if we want our preferred features to find their way into the app we use every day.

**Pull request merged**
