### PR TITLE
Add notes to split transaction

### PR DESCRIPTION
**Pull request by morpheus2891**
Add notes to split transaction

### CODE REVIEW

**Comment by luisdev** [comment]
Is this the implementation for #1475?

**Comment by morpheus2891** [comment]
Yess. Excuse me.  I didn't see the issue.  I implemented 4 years ago but abandoned the project due to lack of time

**Comment by luisdev** [comment]
Thank you. I'm looking forward to testing this. 🙂

**Comment by morpheus2891** [comment]
Thanks 😊

**Comment by guanlisheng** [comment]
thanks @morpheus2891, seems some bak files were pushed by accidents, would you take a look

**Comment by morpheus2891** [comment]
Excuse me. I accidentally loaded winmerge backup files

**Comment by guanlisheng** [comment]
@morpheus2891, can you help to take a look at the failed checks?

+ @luisdev and @wolfsolver as FYI

**Comment by wolfsolver** [comment]
@morpheus2891 I take a look into your code and repo. Seems that you did not update test case for your code in /app/src/test/java/org/moneymanagerex/android/testhelpers/DataHelpers.java. 

To perform testrun, you need to update code at line 109, in method createSplitTransaction. As you see test case does not contain note string parameter, so check failed.

Actual code
```
        // split categories
        SplitCategoriesRepository splitRepo = new SplitCategoriesRepository(context);
        SplitCategory split1 = SplitCategory.create(tx.getId(), 1, -1,
                tx.getTransactionType(), MoneyFactory.fromDouble(25));
        splitRepo.insert(split1);
        SplitCategory split2 = SplitCategory.create(tx.getId(), 1, -1,
                tx.getTransactionType(), MoneyFactory.fromDouble(25));
        splitRepo.insert(split2);
```
To be code, somethings like
....
                tx.getTransactionType(), MoneyFactory.fromDouble(25)**, "note 1"**);
....
                tx.getTransactionType(), MoneyFactory.fromDouble(25)**, "note 2"**);
....

**Comment by wolfsolver** [comment]
@morpheus2891 I try to fix directly on your remo. seems better, but some other minor issue 
in code app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesAdapter.java
https://app.codacy.com/gh/moneymanagerex/android-money-manager-ex/pullRequest?prid=13374052

* Unused import - android.text.TextUtils ==> need to be Remove
* Document empty method body for method  beforeTextChanged
* Document empty method body for method  onTextChanged

**Comment by wolfsolver** [comment]
@morpheus2891 fixed by me
@guanlisheng  check if is all ok and approve

**Comment by wolfsolver** [comment]
example screen from compiled version

image

**Comment by wolfsolver** [comment]
Also close #253

**Review by guanlisheng — APPROVED** [review]

**Comment by morpheus2891** [comment]
Excuse me.  Unfortunately I have been very busy.  I had seen the commit errors and messages.  I would have fixed it today.  You preceded me.  Thank you

**Comment by wolfsolver** [comment]
@morpheus2891 no problem: cooperation is exactly this.

**Comment by morpheus2891** [comment]
Yes. Cooperation is exactly this. As soon as I have more free time I will propose new features and implement them. I'll mention some of them:
- Allow the user to choose the display order of the transaction list;
- Allow the user to create custom reports.

and many others.

I have been using the anMoney app for 17 years but unfortunately it is no longer supported. it's a very good app. Then I discovered MMEX and I think that with some additions it can replace it.

See you soon

**Comment by luisdev** [comment]
> example screen from compiled version
> 
> image

Perfect!
How many characters are allowed in these Notes fields?

**Comment by wolfsolver** [comment]
Same as desktop version. dB was the same. 
I think was some GB :)

**Comment by luisdev** [comment]
I can't wait to test this! But the 2024.01.16.1014 release does not have an apk file in the assets tab on github.

**Comment by morpheus2891** [comment]
on the DB, the NOTES field in the SPLITTRANSACTIONS_V1 table is a TEXT type field. So it should contain 65536 characters

**Comment by morpheus2891** [comment]
> I can't wait to test this! But the 2024.01.16.1014 release does not have an apk file in the assets tab on github.

who should create the apk file? Unfortunately I have problems with Android Studio. I can't compile the apk due to errors on some test libraries and I haven't had time to debug

**Comment by wolfsolver** [comment]
See issue #1528

**Comment by guanlisheng** [comment]
just uploaded.  
also,please turn on the usage data sending  and it helps

**Comment by luisdev** [comment]
Thank you! I'm testing now! :-)

See #1530

**Comment by luisdev** [comment]
So far, no issues or other problems identified.

**Pull request merged**
