### PR TITLE
Currency chart

### PR DESCRIPTION
**Pull request by MisterY**
Initial implementation of #50.
The chart for the last 5 days is shown for the currency pair.

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
can you also update the changelog?

**Comment by MisterY** [comment]
aha, sure!

**Comment by MisterY** [comment]
Is this enough?

**Comment by AlessandroLazzari** [comment]
Insert all under the tag <changelogversion changeDate="February 6, 2015" versionName="2.0.0-beta1">
and describe what it does in a few words this new feature.
Then when I do get the new version update I the date and the version number.
Thanks

**Comment by MisterY** [comment]
Aha, I see. Like this?

**Comment by MisterY** [comment]
I think it's time for 2.0 release. We'll have too many features! It will seem like a new application. :)

**Pull request merged**
