### PR TITLE
Split transaction sum & display

### PR DESCRIPTION
**Pull request by MisterY**
Fix for #96.

### CODE REVIEW

**Comment by AlessandroLazzari** [comment]
This pull request is it complete?

**Comment by MisterY** [comment]
If you want, you can pull this one. I'll check the type change tomorrow and send another one, then.

**Comment by AlessandroLazzari** [comment]
Quiet, there is no hurry! I'm waiting for you to complete all the changes, and when you are ready for your pull request, I will proceed with the merger.

**Comment by MisterY** [comment]
OK, great! :)

**Comment by MisterY** [comment]
This is complete now. Switching the type of the split parts is now handled. You can merge.

**Comment by MisterY** [comment]
@AlessandroLazzari, this piece is complete. We can merge and release beta?

**Comment by AlessandroLazzari** [comment]
Hello Alen, it all works for recurring transactions. I have several exceptions if I try to use the split of the categories in the normal transaction. You can check please?

**Comment by AlessandroLazzari** [comment]
Great. Works fine!

**Pull request merged**
