### PR TITLE
Nestedcategory docs and Budget refinement

### PR DESCRIPTION
**Pull request by wolfsolver**

### CODE REVIEW

**Comment by wolfsolver** [comment]
@guanlisheng I cannot complete work now. Hoping for tomorrow

**Comment by wolfsolver** [comment]
@guanlisheng I cannot complete work now. Hoping for tomorrow

**Comment by wolfsolver** [comment]
Finally, as promise, budget refactor with nested category ready befor EndOfDay (my day:-)

can be merged and close #1376

**Review by guanlisheng — APPROVED** [review]

**Comment by guanlisheng** [comment]
thanks @wolfsolver, you are the man.

The next step might be to consider restoring the previous class category list (expandable like a tree). and this would be applied to reports, and budgets too. thoughts?

classic category list which is more user friendly.
classic_category

new category list is totally flatten, which is a little hard to see and manage
new_category_flatten

**Comment by wolfsolver** [comment]
Absolutely agree.

**Pull request merged**
