### PR TITLE
Fast Category select

### PR DESCRIPTION
**Pull request by vladimir-poleh**
If Category have no children, click to the Category will select it instead of subcategories folding/unfolding.

### CODE REVIEW

**Comment by MisterY** [comment]
Hmmm, I believe this introduces inconsistent behaviour to the form.
The default behaviour of the list does not indicate whether there are any child elements or not. Each "group" element has a down arrow, which is misleading. 
We also introduce some default categories by default, which may not be know to users. Hence, selecting a category without clearly indicating the results of the action would be misleading.
On the other hand, there are fast selectors already on each item, which serve the purpose of quickly selecting an item.
I agree that the current behaviour is also not the ideal one and a better selector would be welcome. 

The most obvious choice would be a checkmark and on OK button. This is actually how the Category selector worked originally. I find that the two-click solution takes 100% more clicks than a one-click solution, hence the current version.

**Comment by vladimir-poleh** [comment]
There is no direct way to hide group indicator for the categories without subcategories, but I'll try to emulate it. Lets wait for this fix before merging.

**Comment by MisterY** [comment]
I'm just wondering if it is worth it, considering that every row contains the selector icon at the right-hand side. Perhaps we could just improve the styling of the selector. See #562

**Comment by vladimir-poleh** [comment]
I have added logic to hide group indicator. Same UI is used for the Categories list but without Select button.

screenshot_20160722-144533 screenshot_20160722-150720

**Comment by MisterY** [comment]
That looks pretty good. Which Android version do you use when testing, btw? Will everything work on Android 4.0.3?

**Comment by vladimir-poleh** [comment]
It was tested on 4.4 and 6.0. Will check on 4.0.3 a bit later.

**Comment by vladimir-poleh** [comment]
Tested on 4.0.3

screenshot_20160722-193027

**Pull request merged**
