### PR TITLE
Make MMEX Android Alive Again! make it work on latest android studio and update dependency and target sdk

### PR DESCRIPTION
**Pull request by tim-hub**
make it work on latest android studio

- upgrade gradle
- updea dependencies
- migrate project to androidX throguh android studio too
- update target sdk version
- temporarly rename app id to `.mmss.fork`, look forwar to change it back to merge back to upstream

---

Hi MMEX team, @vomikan 

 I would like to take responsibility to keep mmex-android alive, because I am a very old user.

 please le me know your thoughts, or I will probably clone one maintain the fork.
 
 
 
 Regards

### CODE REVIEW

**Comment by potestus** [comment]
As an old user in many ways the would be good.

**Review by Hbutlercapone — COMMENTED** [review]
approve changes to work on the latest android studio.

**Review by Hbutlercapone — APPROVED** [review]
Updated #1415

**Review by Hbutlercapone — APPROVED** [review]

**Comment by dennys** [comment]
Could we download this version? F-droid (https://f-droid.org/en/packages/com.money.manager.ex/) is 2019 version

**Pull request merged**
