### PR TITLE
Search notes

### PR DESCRIPTION
**Pull request by MisterY**
Improving the text search for Notes field. 
Fix for #197

### CODE REVIEW

**Comment by guanlisheng** [comment]
May be we should consider FTS

**Comment by MisterY** [comment]
I did not know that existed on SQLite. :)
But I wonder if it would improve the performance significantly, considering we are searching only one field.

However, I *would* like to have an advanced search where we search for a part of text anywhere in transactions. In that case FTS would be great! I'll create a request for it so that we can try it out.

**Comment by AlessandroLazzari** [comment]
http:// <http://developer.android.com/training/search/search.html>
developer.android.com
<http://developer.android.com/training/search/search.html>/training/
<http://developer.android.com/training/search/search.html>search
<http://developer.android.com/training/search/search.html>/
<http://developer.android.com/training/search/search.html>search.html
<http://developer.android.com/training/search/search.html>

But if we want to implement it does not in version 2.0 because it tested
well.

**Comment by MisterY** [comment]
I created #202

**Comment by AlessandroLazzari** [comment]
I can not merge this pull request. can you do the rebase, without the need to I resolve the conflict?

**Comment by MisterY** [comment]
Sure. Will do it right away. Thanks for merging!

**Comment by AlessandroLazzari** [comment]
Please when we do the pull request for the resolution of an issue, we do not modify the structure of the package. If not, it becomes impossible to meger the various pull request. Each pull request changes the structure of the package.

**Comment by MisterY** [comment]
Understood.
Fortunately no real conflicts here. Beyond Compare fitted everything correctly.

**Comment by AlessandroLazzari** [comment]
IMO, we have to set a structure of the package and then do not change it much. If you believe that there are still things (related to reftactor) to edit almost all know that so we discuss it and we organize?
:sweat_smile:

**Comment by MisterY** [comment]
OK. I was wondering if grouping parts by business function (i.e. search, checking account, etc.) instead of technical (activities, fragments, adapters) would make more sense and easier to find when working. Especially later, when we add more code.
I would like to hear your opinion.

**Comment by AlessandroLazzari** [comment]
It could go well, I when I looked at other libraries or other application I
have seen groupings more technical concepts (adapter, database,
notification, services), and little for the business logic (such as, for
example, transactions, research, reports, recurring transaction). I had
started to implement it to the technical solution, but no one forbids us to
run even a hybrid solution.
What I wanted to emphasize with my previous comment, that before you decide
to change the structure of the package and discuss all together.
​

**Comment by MisterY** [comment]
I understand. Whereas I seem to do first, talk later. I'm under the impression that nowadays it is relatively easy to revert any change because the source control tools are so good. That's probably why I let the change initiate the discussion if there is a need for it. I'm happy to change that but I'm just not sure how to do it in practice. :)

**Pull request closed without merging**
