### PR TITLE
NestedCategory Search Transaction with subcategory from category list

### PR DESCRIPTION
**Pull request by wolfsolver**
Search Transaction including subtransaction from category list

image

### CODE REVIEW

**Comment by wolfsolver** [comment]
@guanlisheng let me know when you think that nested category can be consider as released, so I can remove setting switch. Meanwhile I continue developing missing feature like budget and search enhance

**Comment by guanlisheng** [comment]
thanks @wolfsolver . They can coexist for a while and let the end user decide.  

BTW, an expandable category list would be friendly to view and manage. thoughts?

**Comment by guanlisheng** [comment]
once #1700 achieved, it would be time to release.

**Comment by wolfsolver** [comment]
In my list budget is more important than fix  #1700 (that it is more an improvement that an issue related to nested category). So i think that is not necessarily to wait for #1700 completion.

I think that asap budget is refactor new release can be done.

@guanlisheng what do you think?

**Comment by guanlisheng** [comment]
Would you happen to have any detailed ideas about budget refactoring? 

We could process a new release without both.

**Comment by wolfsolver** [comment]
I Think Budget refactor with neested Category will be ready befor EOD. Stay tuned and ready for release :)

**Comment by guanlisheng** [comment]
I c,  such budget refactoring for category makes sense.  and looking forward to it.

**Pull request merged**
