### PR TITLE
Handle Manual, Prompt & Automatic Transaction. See issue #1729

### LINKED ISSUE #1729: Scheduled transactions: Related to 1719
Issue 1719 was closed. 

Thank you for the efforts taken. I have s23 ultra and Android 14. I tried 1034 beta you sent, it gives me a notification but does not give a choice whether to enter the scheduled transaction or not. Sometimes although the transaction is scheduled it is not executed due to some delay.

I would like if it asks me can I enter this transaction or not? Or alternatively when we setup scheduled transaction we can have toggle switch 1. Manual or 2. Automatic entry

### PR DESCRIPTION
**Pull request by wolfsolver**
I have add Schedule Transaction mode.

now in edit you can choise mode (Manual, Prompt, Auto) in according with Desktop version
Only Automatic transaction will be posted if posting is enable in setting

Close #1729

### CODE REVIEW

**Comment by wolfsolver** [comment]
@guanlisheng I'm back thanks to my holidays :)
Can you review and approve?

**Comment by wolfsolver** [comment]
code refine & fix correlation beetween recurrence and recurrenceMode

code code complete.

**Comment by wolfsolver** [comment]
Add multiline support in Recurring Notification

**Comment by guanlisheng** [comment]
thanks @wolfsolver and this is a great improvement.

**Review by guanlisheng — APPROVED** [review]

**Pull request merged**
