### PR TITLE
Report categories and report derivatives completed

### PR DESCRIPTION
**Pull request by AlessandroLazzari**
Fixed also issue: https://github.com/moneymanagerex/android-money-manager-ex/issues/115

### CODE REVIEW

**Comment by MisterY** [comment]
Categories report, there's an exception on search when no results available.

**Comment by MisterY** [comment]
Custom dates are fantastic! Thank you.

**Comment by MisterY** [comment]
The rest seems ok!

**Comment by AlessandroLazzari** [comment]
Thank you for your recommendation. I'll fix.

**Comment by AlessandroLazzari** [comment]
I fixed exception! you can try again when you have time?

**Comment by MisterY** [comment]
There is still one comment left at the end of the line 256. Not sure if this will cause issues.
I'm gonna test now.

**Comment by AlessandroLazzari** [comment]
have you still an exception? I did several tests last night and I had no
problems.
​

**Comment by MisterY** [comment]
No problems now with search now. 
It looks that there is still the comment in the SQL left at the end of the instruction. Perhaps you could just remove it in an online editor? Let me know if you can do that or if I should merge as is.

**Comment by MisterY** [comment]
I'll do that, no worries. It is easier.

**Comment by AlessandroLazzari** [comment]
The comment in the statement, I use it as a token because the where clause
is composed of dynamically, and I need to clear the previous search
criteria, if no added always to the previous policy, and therefore not
functioned more research. It's all correct as well.

2015-04-17 9:04 GMT+02:00 Alen Siljak <notifications@github.com>:

**Comment by AlessandroLazzari** [comment]
Thanks
​

**Comment by MisterY** [comment]
Ah, I see. I was too quick to remove it. So it should be put back? :)

**Comment by AlessandroLazzari** [comment]
Yes it was not removed! The comment is used as a token. If you want I can
fix this evening?
​

**Comment by MisterY** [comment]
OK, I added it back quickly in the online editor.

**Pull request merged**
