### PR TITLE
Fix certain languages ineffective when selected as Application Language

### PR DESCRIPTION
**Pull request by devlearner**
In *Settings* > *General* > *Application Language* :
- fix certain languages not applied when selected in the language list
- added some available/translated languages to language list for selection

n.b. :   this pr modified:
- `scripts/update_translations.py`:   
(a helper script that (seems to) deal with copying Crowdin translated files to their respective language resource folder)
a change is made to copy Hebrew files to the `iw` (language code) folder (instead of `he`)
- `app/src/main/res/values/strings.xml`:   
a string (for the language label "Arabic") is changed and marked non-translatable
**Action needed:**   the updated version would need upload to Crowdin following this pr

### CODE REVIEW

**Comment by MisterY** [comment]
A quick comment - the translated resource strings are copied from Crowdin and, therefore, overwritten every time the translations are updated.

**Comment by MisterY** [comment]
This would be much easier to merge if the issues were separated into multiple merge requests. I'm not sure what the "locale fixes" actually fix. Could you explain the changes and which problem are they solving?
I'm afraid to merge this without a thorough test as the scripts copy the content from Crowdin into the Android project resource files. 
In a pull that affects this many files, I find it a bit difficult to review everything at one time, so splitting the changes into smaller, related groups, would be much more practical.
Also, as mentioned earlier, all the changes in the strings.xml files are useless because they **will** be overwritten the next time the translations are collected from Crowdin project.

**Comment by devlearner** [comment]
Hi @MisterY thank you for your comments.

> A quick comment - the translated resource strings are copied from Crowdin and, therefore, overwritten every time the translations are updated.

I was aware of this.  I just thought to update each language manually in the meantime pending another update.   Turns out it clutters the diff log quite a bit; I've removed them and just made a change in the 'master' `strings.xml` file (more below).

> I'm afraid to merge this without a thorough test as the scripts copy the content from Crowdin into the Android project resource files.

I'm alive to the translations on Crowdin.   I think the workflow for the Crowdin translations would be roughly this (from my humble understanding) :
- A 'master' file (the original English version and base for translation), namely `app/src/main/res/values/strings.xml` is uploaded (by you) to Crowdin for translation
<br>(Before a release, or when updating translations)
- The translations on Crowdin would be exported/downloaded in bulk as a zip archive
- A helper script `scripts/update_translations.py` would be invoked to copy the translation files to their respective resources folder

Due to changes in the pr, there's a necessary change to the 'master' `strings.xml` file: namely that the string "Arabic" is marked as non-translatable.  So with this PR the master file `app/src/main/res/values/strings.xml` will need to be uploaded to Crowdin again to reflect the change (removing one string for translation) on the Crowdin platform.

Sorry for the inconvenience with the pr.   My infelicities of expression probably made it look a little bit 'scary' than it does but they are pretty innocuous changes in fact.   I've edited my post above for better clarity.   Would you mind if going through it again?   I'm open to breaking down the pr but, after removing the `strings` clutter, the changes seem quite minimal.

Please feel free to let me know if you wish any changes.

Thank you once again for your review!

**Comment by MisterY** [comment]
Thanks. I'll need to try this out. Hopefully this Sunday.

**Pull request merged**
